version: "3.7"

services:
  my-blog:
    build:
      context: .
      dockerfile: Dockerfile
    image: myblogcontainer
    environment:
      NODE_ENV: production
    ports:
      - "9002:80"
    container_name: my-blog
    restart: always